# Generated by Django 5.1.6 on 2025-02-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_complted_task_compelted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='compelted',
            new_name='completed',
        ),
    ]
